import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";
import Modal from "@/components/Modal";
import Registermodal from "@/components/modals/RegisterModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <body>
        <>
        
        <Registermodal/>
        <Layout>
          {children}
        </Layout>
        </>
        
      </body>
    </html>
  );
}
