import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";
import Modal from "@/components/Modal";
import Registermodal from "@/components/modals/RegisterModal";
import LoginModal from "@/components/modals/LoginModal";
import { Toaster } from "react-hot-toast";

// Import the client component wrapper for SessionProvider
import NextAuthProvider from "@/components/providers/NextAuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      
        <NextAuthProvider>
          <Toaster />
          <Registermodal/>
          <LoginModal/>
          <Toaster />
          <Layout>
            {children}
          </Layout>
        </NextAuthProvider>
      </body>
    </html>
  );
}

